[project]
name = "fec-example"
version = "0.1.0"
description = "FEC data example"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "pandas>=2.0.0",
    "duckdb>=0.9.0",
    "matplotlib>=3.8.0",
    "requests>=2.31.0",
]
