#!/usr/bin/env python3
"""Build notebooks/cross_company.ipynb from declarative cell definitions.

Why a builder? Authoring .ipynb JSON by hand is painful; this script keeps the
notebook editable in code (or in Jupyter directly — the .ipynb is the output)
while making it easy to regenerate from scratch:

    uv run python tools/build_cross_company_nb.py

The notebook is committed to git after generation; the builder is kept for
future regeneration.
"""
from pathlib import Path

import nbformat as nbf


def md(*parts: str):
    return nbf.v4.new_markdown_cell("\n".join(parts).strip() + "\n")


def code(*parts: str):
    return nbf.v4.new_code_cell("\n".join(parts).rstrip() + "\n")


# ──────────────────────────────────────────────────────────────────────────────
# Notebook content
# ──────────────────────────────────────────────────────────────────────────────

CELLS = [

    md(
        "# Cross-Company FEC Analysis",
        "",
        "A modern port of the original SAS pipeline (see "
        "[the design doc](../docs-src/sas-port.md) for context).",
        "",
        "The SAS code (~1,100 lines of `DATA` steps and `PROC TABULATE`) takes",
        "Schedule-A receipts for Fortune-500 employees, joins committee→party",
        "lookups, infers gender by first name, and applies the **60 % rule** to",
        "assign each contributor to a party. This notebook re-expresses the same",
        "11-step pipeline as ~10 DuckDB CTEs and pandas calls — and pushes",
        "further with multi-company comparisons, time series, and the embedded",
        "`committee.party` field that OpenFEC's API now provides directly.",
        "",
        "## What this notebook produces",
        "",
        "1. **`stats5all`** — final contributor-level table (one row per person, 60 %-rule classified).",
        "2. **`saspac3all`** — final contribution-level table (one row per transaction).",
        "3. **`company_contributors`** — SAS-parity summary (one row per employer, contributor counts + dollars by D/R/Other × M/F/U).",
        "4. **`company_contributions`** — SAS-parity summary (one row per employer, transaction counts + dollars).",
        "5. Cross-company stacked bars, monthly time series, state distribution, top recipient committees.",
        "",
        "Every section maps back to specific lines in `sascsvc19.sas` so a SAS",
        "reader can cross-reference.",
    ),

    md(
        "## 1. Configuration",
        "",
        "Five Fortune-500 employers with varied political profiles, the same",
        "2019–2020 cycle the SAS analysis covered. The notebook auto-skips any",
        "company whose JSON isn't in `output/schedule_a/` — fetch what you have,",
        "the rest just don't appear.",
    ),

    code(
        "# Employers to include — order = display order in charts/tables.",
        "COMPANIES = [",
        "    'TRACTOR SUPPLY',",
        "    'MICROSOFT',",
        "    'EXXON MOBIL',",
        "    'WALMART',",
        "    'LOCKHEED MARTIN',",
        "]",
        "",
        "MIN_DATE = '2019-01-01'",
        "MAX_DATE = '2020-12-31'",
        "PARTY_THRESHOLD = 0.60   # SAS 60 % rule, sascsvc19.sas:534+",
        "GENDER_HIGH_CONF = {'male', 'female'}   # equivalent to SAS probability >= 0.9 cutoff",
        "PAGES_PER_COMPANY = 2    # 200 records each — keeps cold-fetch under a minute",
    ),

    code(
        "import json",
        "import os",
        "import re",
        "from datetime import datetime",
        "from pathlib import Path",
        "",
        "import duckdb",
        "import matplotlib.pyplot as plt",
        "import pandas as pd",
        "from IPython.display import display, Markdown",
        "",
        "%matplotlib inline",
        "",
        "# Resolve paths from project root whether launched from notebooks/ or root.",
        "_here = Path.cwd()",
        "if _here.name == 'notebooks':",
        "    os.chdir(_here.parent)",
        "",
        "from fec_client import FECClient   # disk-cached OpenFEC client",
        "",
        "ROOT = Path.cwd()",
        "CSV_DIR = ROOT / 'csv'",
        "SCHEDULE_A_DIR = ROOT / 'output' / 'schedule_a'",
        "TABLES_DIR = ROOT / 'output' / 'tables'",
        "CHARTS_DIR = ROOT / 'output' / 'charts'",
        "TABLES_DIR.mkdir(parents=True, exist_ok=True)",
        "CHARTS_DIR.mkdir(parents=True, exist_ok=True)",
        "",
        "print(f'project root : {ROOT}')",
        "print(f'schedule_a   : {SCHEDULE_A_DIR}')",
        "print(f'tables out   : {TABLES_DIR}')",
    ),

    md(
        "## 2. Lookups",
        "",
        "The SAS pipeline takes four lookup tables (`AllPacs`, `Aristotle`,",
        "`name_gender`, `CompanyRank`) plus the `$COMPANYF.`/`$AGENCYF.`",
        "PROC FORMAT mappings. We replicate them inline.",
        "",
        "- **`AllPacs.xslx.csv`** — ~35K rows committee_id → party affiliation (real SAS lookup, bundled in `csv/`)",
        "- **`Aristotle1.xlsx.csv`** — 25 party codes → full party name (real SAS lookup, bundled in `csv/`)",
        "- **Gender** — `gender-guesser` library replaces `name_gender.csv` (≈ 50K names, MIT-licensed)",
        "- **State name** — inline US Postal abbrev → full name dict (replaces `stnamel()`)",
        "- **Display company name** — inline dict (replaces `$COMPANYF.` formats)",
    ),

    code(
        "allpacs   = pd.read_csv(CSV_DIR / 'AllPacs.xslx.csv')",
        "aristotle = pd.read_csv(CSV_DIR / 'Aristotle1.xlsx.csv')",
        "",
        "# Display names for our 5 employers (replaces SAS $COMPANYF. PROC FORMAT).",
        "COMPANY_DISPLAY = {",
        "    'TRACTOR SUPPLY':  'Tractor Supply',",
        "    'MICROSOFT':       'Microsoft',",
        "    'EXXON MOBIL':     'Exxon Mobil',",
        "    'WALMART':         'Walmart',",
        "    'LOCKHEED MARTIN': 'Lockheed Martin',",
        "}",
        "",
        "# Replaces SAS stnamel(state) — 50 states + DC + 5 territories.",
        "STATE_NAMES = {",
        "    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas',",
        "    'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware',",
        "    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho',",
        "    'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas',",
        "    'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland',",
        "    'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi',",
        "    'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada',",
        "    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NY': 'New York',",
        "    'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma',",
        "    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',",
        "    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah',",
        "    'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia',",
        "    'WI': 'Wisconsin', 'WY': 'Wyoming', 'DC': 'District of Columbia',",
        "    'PR': 'Puerto Rico', 'VI': 'Virgin Islands', 'GU': 'Guam', 'AS': 'American Samoa',",
        "    'MP': 'Northern Mariana Islands',",
        "}",
        "",
        "print(f'AllPacs   : {len(allpacs):>6,} rows  → covers {allpacs[\"Political Affiliation\"].nunique()} party codes')",
        "print(f'Aristotle : {len(aristotle):>6,} rows  → {len(aristotle)} party codes')",
        "print(f'States    : {len(STATE_NAMES):>6,} entries')",
        "display(aristotle)",
    ),

    md(
        "## 3. Fetch — Schedule A (individual contributions)",
        "",
        "Each fetch is disk-cached; subsequent re-runs are ~instant. The cache",
        "keys the canonical request URI, so any `(employer, date range, page)`",
        "tuple only hits the API once.",
        "",
        "We also flatten the **embedded `committee` object** in the API response",
        "into top-level columns (`committee_party_embedded`,",
        "`committee_type_full`, `committee_designation_full`). The SAS code",
        "needed `AllPacs.csv` because the bulk-data CSVs didn't carry party",
        "info; the modern API does — so this lets us cross-check and fill gaps.",
    ),

    code(
        "client = FECClient(api_key=os.environ.get('FEC_API_KEY', 'Kgkivmpbsy1rehiCuTcd8gVHxzwQFRcSDsrVhQJm'))",
        "",
        "def fetch_company(employer: str) -> pd.DataFrame:",
        "    \"\"\"Fetch `PAGES_PER_COMPANY` pages from the API (cached) and flatten",
        "    the nested `committee` object into top-level columns.\"\"\"",
        "    records = client.schedule_a_pages(",
        "        employer, MIN_DATE, MAX_DATE,",
        "        max_pages=PAGES_PER_COMPANY,",
        "    )",
        "    if not records:",
        "        return pd.DataFrame()",
        "    df = pd.DataFrame(records)",
        "    # Flatten the nested committee dict into top-level columns we'll use.",
        "    cmte = df.get('committee').apply(",
        "        lambda c: c if isinstance(c, dict) else {}",
        "    )",
        "    df['committee_party_embedded']      = cmte.apply(lambda c: c.get('party'))",
        "    df['committee_type_full']           = cmte.apply(lambda c: c.get('committee_type_full'))",
        "    df['committee_designation_full']    = cmte.apply(lambda c: c.get('designation_full'))",
        "    df['company']                        = employer",
        "    return df",
        "",
        "frames = []",
        "for employer in COMPANIES:",
        "    print(f'• {employer}')",
        "    try:",
        "        f = fetch_company(employer)",
        "    except Exception as e:",
        "        print(f'   ! skip — {e}')",
        "        continue",
        "    if f.empty:",
        "        print('   ! no rows')",
        "        continue",
        "    print(f'   ✓ {len(f):,} rows')",
        "    frames.append(f)",
        "",
        "raw = pd.concat(frames, ignore_index=True)",
        "ACTIVE_COMPANIES = list(raw['company'].unique())",
        "print(f'\\nCombined: {len(raw):,} rows · {len(ACTIVE_COMPANIES)} companies · {raw[\"committee_id\"].nunique():,} distinct committees')",
        "raw[['company', 'contributor_name', 'contribution_receipt_amount',",
        "     'committee_name', 'committee_party_embedded',",
        "     'committee_type_full']].head(5)",
    ),

    md(
        "## 4. SASPAC — committee → party enrichment",
        "",
        "*SAS reference: `sascsvc19.sas:3–12` (the PROC FEDSQL that builds SASPAC)*",
        "",
        "Party resolution falls back through three sources:",
        "",
        "1. **`committee.party`** embedded in the API response (preferred — authoritative for committees that have a registered party)",
        "2. **`AllPacs.xslx.csv`** lookup on `committee_id` (the SAS source-of-truth)",
        "3. **`'N'`** (None / Nonpartisan) if neither resolves",
        "",
        "Then `Aristotle1.xlsx.csv` joins the 25-code party catalog onto the resolved code.",
    ),

    code(
        "con = duckdb.connect(':memory:')",
        "con.register('raw', raw)",
        "con.register('allpacs', allpacs)",
        "con.register('aristotle', aristotle)",
        "",
        "saspac = con.execute(\"\"\"",
        "    WITH joined AS (",
        "        SELECT",
        "            r.company,",
        "            r.contributor_name,",
        "            UPPER(TRIM(r.contributor_first_name)) AS first,",
        "            UPPER(TRIM(r.contributor_last_name))  AS last,",
        "            r.contributor_employer AS division,",
        "            r.contributor_occupation AS occupation,",
        "            r.contributor_city  AS city,",
        "            r.contributor_state AS state,",
        "            CAST(r.contributor_zip AS VARCHAR) AS zip_raw,",
        "            r.committee_id,",
        "            r.committee_name   AS committee,",
        "            r.contribution_receipt_amount AS contribution,",
        "            r.contribution_receipt_date    AS receipt_date,",
        "            r.committee_party_embedded,",
        "            r.committee_type_full,",
        "            r.committee_designation_full,",
        "            a.\\\"Political Affiliation\\\" AS allpacs_party",
        "        FROM raw r",
        "        LEFT JOIN allpacs a ON r.committee_id = a.committee_id",
        "    )",
        "    SELECT",
        "        j.*,",
        "        -- Three-tier party resolution",
        "        COALESCE(",
        "            UPPER(NULLIF(TRIM(j.committee_party_embedded), '')),",
        "            UPPER(NULLIF(TRIM(j.allpacs_party), '')),",
        "            'N'",
        "        ) AS code,",
        "        ar.Party AS party",
        "    FROM joined j",
        "    LEFT JOIN aristotle ar ON ar.Code = COALESCE(",
        "        UPPER(NULLIF(TRIM(j.committee_party_embedded), '')),",
        "        UPPER(NULLIF(TRIM(j.allpacs_party), '')),",
        "        'N'",
        "    )",
        "\"\"\").df()",
        "",
        "# How often did each source resolve the party?",
        "resolved = pd.DataFrame({",
        "    'embedded (API)': saspac['committee_party_embedded'].notna().sum(),",
        "    'AllPacs CSV'   : saspac['committee_party_embedded'].isna().sum() - (saspac['code'] == 'N').sum() + ",
        "                      ((saspac['allpacs_party'].notna()) & (saspac['committee_party_embedded'].notna())).sum() * 0,",
        "    \"fell to 'N'\"  : (saspac['code'] == 'N').sum(),",
        "}, index=['contributions']).T",
        "resolved['share'] = (resolved['contributions'] / len(saspac) * 100).round(1).astype(str) + '%'",
        "display(Markdown('### Party resolution by source'))",
        "display(resolved)",
        "saspac[['company', 'committee', 'committee_party_embedded',",
        "        'allpacs_party', 'code', 'party']].head(6)",
    ),

    md(
        "## 5. SASPAC2 — gender (`name_gender` ≥ 0.9 threshold) + statename",
        "",
        "*SAS reference: `sascsvc19.sas:45–76, 93–99` (merge name_gender, apply",
        "probability ≥ 0.9 cutoff; stnamel() for state name)*",
        "",
        "`gender-guesser` returns one of `{male, female, mostly_male, mostly_female,",
        "andy, unknown}`. SAS's `≥ 0.9` probability threshold maps cleanly to",
        "*only* `male`/`female` → assign M/F; everything else → `'U'`.",
    ),

    code(
        "import gender_guesser.detector as gd",
        "detector = gd.Detector(case_sensitive=False)",
        "",
        "def infer_gender(first: str) -> str:",
        "    if not isinstance(first, str) or not first.strip():",
        "        return 'U'",
        "    # gender-guesser wants Title-case; lowercase falls back to dictionary keys.",
        "    raw = detector.get_gender(first.strip().capitalize())",
        "    if raw == 'male':",
        "        return 'M'",
        "    if raw == 'female':",
        "        return 'F'",
        "    return 'U'      # mostly_*, andy, unknown — SAS treats all as U",
        "",
        "saspac2 = saspac.copy()",
        "saspac2['gender']    = saspac2['first'].map(infer_gender)",
        "saspac2['statename'] = saspac2['state'].map(STATE_NAMES).fillna('Not Available')",
        "",
        "print('Gender distribution (transactions):')",
        "print(saspac2['gender'].value_counts(dropna=False).to_string())",
        "print()",
        "print('Top 6 states (transactions):')",
        "print(saspac2['statename'].value_counts().head(6).to_string())",
    ),

    md(
        "## 6. SASPAC3 — mParty + zip5 + `compervar`",
        "",
        "*SAS reference: `sascsvc19.sas:83–106` (the SASPAC3 DATA step)*",
        "",
        "- **`mParty`** rolls 25 party codes up to **Democrat / Republican / Other**.",
        "- **`zip5`** strips the +4 suffix and pads to 5 digits — `'37027-1234'` → `'37027'`.",
        "- **`compervar`** = `COMPANY - LASTNAME - ZIP5` — the unique-person key the 60 % rule needs.",
    ),

    code(
        "con.register('saspac2', saspac2)",
        "saspac3 = con.execute(\"\"\"",
        "    SELECT",
        "        *,",
        "        CASE",
        "            WHEN code = 'D' THEN 'Democrat'",
        "            WHEN code = 'R' THEN 'Republican'",
        "            ELSE 'Other'",
        "        END AS mParty,",
        "        LPAD(",
        "            COALESCE(",
        "                NULLIF(REGEXP_REPLACE(zip_raw, '\\\\D', '', 'g'), ''),",
        "                '00000'",
        "            ),",
        "            5, '0'",
        "        )[1:5] AS zip5,",
        "        contribution AS contribsum",
        "    FROM saspac2",
        "\"\"\").df()",
        "",
        "saspac3['compervar'] = (",
        "    saspac3['company'].str.strip() + ' - ' +",
        "    saspac3['last'].fillna('').str.strip() + ' - ' +",
        "    saspac3['zip5']",
        ")",
        "",
        "# Cast date once for downstream resampling.",
        "saspac3['receipt_date'] = pd.to_datetime(saspac3['receipt_date'], errors='coerce')",
        "",
        "print(f'SASPAC3 (contribution-level): {len(saspac3):,} rows × {saspac3.shape[1]} cols')",
        "print(f'Unique compervars (people)  : {saspac3[\"compervar\"].nunique():,}')",
        "print(f'mParty distribution:')",
        "print('  ', saspac3['mParty'].value_counts().to_string().replace('\\n', '\\n   '))",
    ),

    md(
        "## 7. STATS5 — apply the 60 % rule",
        "",
        "*SAS reference: `sascsvc19.sas:532–563` (the STATS4 DATA step), `:618–622` (STATS5 join with Aristotle)*",
        "",
        "Per-person aggregation: build a sum column for every party code (`Dsum`, `Rsum`, …),",
        "compute each person's total, then mark them as party *X* iff `Xsum / total ≥ 0.6`.",
        "Otherwise `'N'`. SAS does this in 25 `IF` statements; DuckDB collapses it to one `CASE`.",
        "",
        "**Output: `stats5` — one row per unique contributor.** This is the canonical contributor-level dataset.",
    ),

    code(
        "con.register('saspac3', saspac3)",
        "",
        "# All 25 Aristotle party codes — same set as SAS sasformats.sas / Aristotle1.csv.",
        "PARTY_CODES = list(aristotle['Code'])",
        "",
        "sum_cols = ',\\n        '.join(",
        "    f\"SUM(CASE WHEN code = '{c}' THEN contribsum ELSE 0 END) AS \\\"{c}sum\\\"\"",
        "    for c in PARTY_CODES",
        ")",
        "rule_cases = '\\n            '.join(",
        "    f\"WHEN \\\"{c}sum\\\" > 0 AND \\\"{c}sum\\\" / contribsum >= {PARTY_THRESHOLD} THEN '{c}'\"",
        "    for c in PARTY_CODES",
        ")",
        "",
        "stats5 = con.execute(f\"\"\"",
        "    WITH person_sums AS (",
        "        SELECT",
        "            compervar,",
        "            ANY_VALUE(company)      AS company,",
        "            ANY_VALUE(contributor_name) AS contributor,",
        "            ANY_VALUE(first)        AS first,",
        "            ANY_VALUE(last)         AS last,",
        "            ANY_VALUE(occupation)   AS occupation,",
        "            ANY_VALUE(city)         AS city,",
        "            ANY_VALUE(state)        AS state,",
        "            ANY_VALUE(statename)    AS statename,",
        "            ANY_VALUE(zip5)         AS zip,",
        "            ANY_VALUE(gender)       AS gender,",
        "            COUNT(*)                AS \"_FREQ_\",",
        "            SUM(contribsum)         AS contribsum,",
        "            {sum_cols}",
        "        FROM saspac3",
        "        GROUP BY compervar",
        "    )",
        "    SELECT",
        "        p.*,",
        "        CASE",
        "            {rule_cases}",
        "            ELSE 'N'",
        "        END AS pCode,",
        "        CASE",
        "            {rule_cases}",
        "            ELSE 'N'",
        "        END AS _pCode_repeat -- only needed once; kept for symmetry",
        "    FROM person_sums p",
        "\"\"\").df()",
        "stats5 = stats5.drop(columns=['_pCode_repeat'])",
        "",
        "# Major-party roll-up (matches SAS mParty assignment in STATS4)",
        "stats5['mParty'] = stats5['pCode'].map(",
        "    lambda c: 'Democrat' if c == 'D' else ('Republican' if c == 'R' else 'Other')",
        ")",
        "stats5 = stats5.merge(",
        "    aristotle.rename(columns={'Code': 'pCode', 'Party': 'PARTY'}),",
        "    on='pCode', how='left',",
        ")",
        "",
        "print(f'STATS5 (contributor-level): {len(stats5):,} rows × {stats5.shape[1]} cols')",
        "print()",
        "print('pCode distribution:')",
        "print(stats5['pCode'].value_counts().head(8).to_string())",
        "print()",
        "print('mParty distribution:')",
        "print(stats5['mParty'].value_counts().to_string())",
    ),

    code(
        "# Sample of the final contributor-level table",
        "preview_cols = ['company', 'contributor', 'state', 'zip', 'gender',",
        "                'Dsum', 'Rsum', 'contribsum', 'pCode', 'PARTY']",
        "stats5[preview_cols].head(10)",
    ),

    md(
        "## 8. Output A — `company_contributors`",
        "",
        "*SAS reference: `stats5xle.sas:274–522` (the `companyxl` DATA step + PROC SUMMARY pivot)*",
        "",
        "One row per employer with the full SAS-parity column set:",
        "",
        "- `Contributor_Count`, `contribsum`",
        "- Democrat: `Dnum`, `Dsumc`, `DMnum`/`DMsum`, `DFnum`/`DFsum`, `DUnum`/`DUsum`",
        "- Republican: `Rnum`, `Rsumc`, `RMnum`/`RMsum`, `RFnum`/`RFsum`, `RUnum`/`RUsum`",
        "- Other: `Onum`, `Osumc`, `OMnum`/`OMsum`, `OFnum`/`OFsum`, `OUnum`/`OUsum`",
        "",
        "This is the dataset behind SAS's `company_contributors.xlsx`.",
    ),

    code(
        "def contributor_summary(s5: pd.DataFrame) -> pd.DataFrame:",
        "    \"\"\"Build the company_contributors table (one row per employer).\"\"\"",
        "    out = []",
        "    for company, g in s5.groupby('company', sort=False):",
        "        row = {",
        "            'Company': COMPANY_DISPLAY.get(company, company),",
        "            'Contributor_Count': len(g),",
        "            'contribsum': g['contribsum'].sum(),",
        "        }",
        "        for letter, name in [('D', 'Democrat'), ('R', 'Republican'), ('O', 'Other')]:",
        "            party_g = g[g['mParty'] == name]",
        "            row[f'{letter}num']  = len(party_g)",
        "            row[f'{letter}sumc'] = party_g['contribsum'].sum()",
        "            for gender_code in ['M', 'F', 'U']:",
        "                gg = party_g[party_g['gender'] == gender_code]",
        "                row[f'{letter}{gender_code}num'] = len(gg)",
        "                row[f'{letter}{gender_code}sum'] = gg['contribsum'].sum()",
        "        out.append(row)",
        "    return pd.DataFrame(out)",
        "",
        "company_contributors = contributor_summary(stats5)",
        "company_contributors",
    ),

    md(
        "## 9. Output B — `company_contributions`",
        "",
        "*SAS reference: `saspac3xle.sas:168–334`*",
        "",
        "One row per employer at the **transaction** level. Same shape as Output A,",
        "but `Dnum` counts transactions to D-mapped committees (not unique people),",
        "and party comes from the *committee*, not the 60 % rule.",
    ),

    code(
        "def contribution_summary(s3: pd.DataFrame) -> pd.DataFrame:",
        "    out = []",
        "    for company, g in s3.groupby('company', sort=False):",
        "        row = {",
        "            'Company': COMPANY_DISPLAY.get(company, company),",
        "            'Contribution_Count': len(g),",
        "            'contribsum': g['contribsum'].sum(),",
        "        }",
        "        for letter, name in [('D', 'Democrat'), ('R', 'Republican'), ('O', 'Other')]:",
        "            party_g = g[g['mParty'] == name]",
        "            row[f'{letter}num'] = len(party_g)",
        "            row[f'{letter}sum'] = party_g['contribsum'].sum()",
        "            for gender_code in ['M', 'F', 'U']:",
        "                gg = party_g[party_g['gender'] == gender_code]",
        "                row[f'{letter}{gender_code}num'] = len(gg)",
        "                row[f'{letter}{gender_code}sum'] = gg['contribsum'].sum()",
        "        out.append(row)",
        "    return pd.DataFrame(out)",
        "",
        "company_contributions = contribution_summary(saspac3)",
        "company_contributions",
    ),

    md(
        "## 10. Why the two summaries differ",
        "",
        "Same employer, same money, two different counts. **Contributions** sees",
        "every donation; **Contributors** sees every unique donor. The ratio",
        "(transactions per person) tells you how transaction-heavy each",
        "employee base is.",
    ),

    code(
        "compare = company_contributions[['Company', 'Contribution_Count']].merge(",
        "    company_contributors[['Company', 'Contributor_Count', 'contribsum']],",
        "    on='Company',",
        ")",
        "compare['txns_per_person'] = (",
        "    compare['Contribution_Count'] / compare['Contributor_Count']",
        ").round(2)",
        "compare['contribsum'] = compare['contribsum'].map('${:,.0f}'.format)",
        "compare",
    ),

    md(
        "## 11. Cross-company visualizations",
        "",
        "These are the views the SAS code never produced (its outputs are",
        "per-company PROC TABULATE pages). Easier to compare employers side-by-side.",
    ),

    code(
        "PARTY_COLORS = {'Democrat': '#3b82f6', 'Republican': '#ef4444', 'Other': '#94a3b8'}",
        "",
        "def stacked_bar(df, value_col, title, ylabel, ax):",
        "    pivot = df.pivot(index='Company', columns='mParty', values=value_col).fillna(0)",
        "    for party in ['Democrat', 'Republican', 'Other']:",
        "        if party not in pivot.columns:",
        "            pivot[party] = 0",
        "    pivot = pivot[['Democrat', 'Republican', 'Other']]",
        "    pivot.plot(kind='bar', stacked=True, ax=ax,",
        "               color=[PARTY_COLORS[p] for p in pivot.columns],",
        "               edgecolor='white', width=0.7)",
        "    ax.set_title(title, fontsize=12, fontweight='bold')",
        "    ax.set_xlabel('')",
        "    ax.set_ylabel(ylabel)",
        "    ax.tick_params(axis='x', rotation=20)",
        "    ax.legend(title='Party', frameon=False, fontsize=9)",
        "    ax.grid(axis='y', alpha=0.3)",
        "    ax.spines['top'].set_visible(False)",
        "    ax.spines['right'].set_visible(False)",
        "",
        "# Build long-form views for plotting",
        "people_long = stats5.assign(",
        "    Company=lambda d: d['company'].map(COMPANY_DISPLAY).fillna(d['company'])",
        ").groupby(['Company', 'mParty']).size().reset_index(name='people')",
        "",
        "dollars_long = stats5.assign(",
        "    Company=lambda d: d['company'].map(COMPANY_DISPLAY).fillna(d['company'])",
        ").groupby(['Company', 'mParty'])['contribsum'].sum().reset_index()",
        "",
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))",
        "stacked_bar(people_long,  'people',     'Unique contributors (60 % rule)', 'people',  ax1)",
        "stacked_bar(dollars_long, 'contribsum', 'Total dollars by classified party', 'dollars', ax2)",
        "ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'${x/1000:.0f}K'))",
        "plt.suptitle('Cross-company party breakdown', fontsize=14, fontweight='bold')",
        "plt.tight_layout()",
        "out_path = CHARTS_DIR / 'cross_company_party_stack.png'",
        "plt.savefig(out_path, dpi=140, bbox_inches='tight')",
        "print(f'saved → {out_path}')",
        "plt.show()",
    ),

    md(
        "### Monthly contribution time-series",
        "",
        "Where in 2019–2020 did the money flow? The 2020 election shows up clearly.",
    ),

    code(
        "monthly = (",
        "    saspac3.assign(month=saspac3['receipt_date'].dt.to_period('M').dt.to_timestamp())",
        "          .groupby(['company', 'month', 'mParty'])['contribsum'].sum()",
        "          .reset_index()",
        ")",
        "",
        "fig, axes = plt.subplots(len(ACTIVE_COMPANIES), 1,",
        "                         figsize=(11, 2.2 * len(ACTIVE_COMPANIES)),",
        "                         sharex=True)",
        "if len(ACTIVE_COMPANIES) == 1:",
        "    axes = [axes]",
        "",
        "for ax, company in zip(axes, ACTIVE_COMPANIES):",
        "    g = monthly[monthly['company'] == company]",
        "    for party in ['Democrat', 'Republican', 'Other']:",
        "        gp = g[g['mParty'] == party]",
        "        if gp.empty:",
        "            continue",
        "        ax.plot(gp['month'], gp['contribsum'],",
        "                label=party, color=PARTY_COLORS[party], linewidth=2)",
        "    ax.set_title(COMPANY_DISPLAY.get(company, company), fontsize=10, loc='left')",
        "    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'${x/1000:.0f}K'))",
        "    ax.grid(axis='y', alpha=0.3)",
        "    ax.legend(frameon=False, fontsize=8, loc='upper left')",
        "    ax.spines['top'].set_visible(False)",
        "    ax.spines['right'].set_visible(False)",
        "",
        "axes[-1].set_xlabel('Month')",
        "plt.suptitle('Monthly contributions by month and party',",
        "             fontsize=13, fontweight='bold')",
        "plt.tight_layout()",
        "out_path = CHARTS_DIR / 'cross_company_monthly.png'",
        "plt.savefig(out_path, dpi=140, bbox_inches='tight')",
        "print(f'saved → {out_path}')",
        "plt.show()",
    ),

    md(
        "### Top contributing states",
        "",
        "Which states show up most in this data? Combined view across all companies.",
    ),

    code(
        "state_totals = (",
        "    saspac3.groupby('statename')",
        "          .agg(transactions=('contribsum', 'size'),",
        "               dollars=('contribsum', 'sum'))",
        "          .sort_values('dollars', ascending=False)",
        "          .head(15)",
        ")",
        "",
        "fig, ax = plt.subplots(figsize=(11, 5))",
        "bars = ax.barh(state_totals.index[::-1], state_totals['dollars'][::-1],",
        "               color='#4f46e5', edgecolor='white')",
        "ax.set_xlabel('Total contributions (dollars)')",
        "ax.set_title('Top 15 contributing states (across all employers)',",
        "             fontsize=12, fontweight='bold')",
        "ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'${x/1000:.0f}K'))",
        "ax.grid(axis='x', alpha=0.3)",
        "ax.spines['top'].set_visible(False)",
        "ax.spines['right'].set_visible(False)",
        "for bar, value in zip(bars, state_totals['dollars'][::-1]):",
        "    ax.text(value, bar.get_y() + bar.get_height() / 2,",
        "            f'  ${value/1000:.0f}K', va='center', fontsize=8, color='#475569')",
        "plt.tight_layout()",
        "out_path = CHARTS_DIR / 'cross_company_top_states.png'",
        "plt.savefig(out_path, dpi=140, bbox_inches='tight')",
        "print(f'saved → {out_path}')",
        "plt.show()",
    ),

    md(
        "### Committee-type breakdown",
        "",
        "Where the money lands. `committee_type_full` distinguishes Candidate",
        "committees from PACs / Super-PACs / party committees, etc.",
    ),

    code(
        "ctype = saspac3['committee_type_full'].fillna('Unknown').value_counts()",
        "",
        "fig, ax = plt.subplots(figsize=(8, 5))",
        "colors = plt.cm.tab10.colors",
        "ax.pie(ctype.values, labels=ctype.index, colors=colors[:len(ctype)],",
        "       autopct='%1.1f%%', startangle=90, wedgeprops={'edgecolor': 'white'})",
        "ax.set_title('Recipient committee types (all transactions)',",
        "             fontsize=12, fontweight='bold')",
        "plt.tight_layout()",
        "out_path = CHARTS_DIR / 'cross_company_committee_types.png'",
        "plt.savefig(out_path, dpi=140, bbox_inches='tight')",
        "print(f'saved → {out_path}')",
        "plt.show()",
    ),

    md(
        "### Top recipient committees per company",
        "",
        "Which PACs / candidates / parties received the most money from each employer base?",
    ),

    code(
        "top_per_company = []",
        "for company in ACTIVE_COMPANIES:",
        "    g = saspac3[saspac3['company'] == company]",
        "    top = (g.groupby(['committee', 'mParty'])",
        "             .agg(transactions=('contribsum', 'size'),",
        "                  dollars=('contribsum', 'sum'))",
        "             .sort_values('dollars', ascending=False)",
        "             .head(5)",
        "             .reset_index()",
        "             .assign(Company=COMPANY_DISPLAY.get(company, company)))",
        "    top_per_company.append(top)",
        "",
        "top_committees = pd.concat(top_per_company, ignore_index=True)",
        "top_committees['dollars'] = top_committees['dollars'].map('${:,.0f}'.format)",
        "top_committees[['Company', 'committee', 'mParty', 'transactions', 'dollars']]",
    ),

    md(
        "## 12. Save SAS-parity outputs",
        "",
        "Written to `output/tables/`; the existing build-site picks them up under",
        "the [Data tab](../../data/) automatically.",
    ),

    code(
        "company_contributors.to_csv(TABLES_DIR / 'company_contributors.csv', index=False)",
        "company_contributions.to_csv(TABLES_DIR / 'company_contributions.csv', index=False)",
        "stats5.head(200).to_csv(TABLES_DIR / 'stats5all_sample.csv', index=False)",
        "saspac3.head(500).to_csv(TABLES_DIR / 'saspac3all_sample.csv', index=False)",
        "",
        "# Bundle the two contributor/contribution summaries in one Excel workbook",
        "# (parity with SAS's company_contributors.xlsx + company_contributions.xlsx)",
        "with pd.ExcelWriter(TABLES_DIR / 'company_summaries.xlsx', engine='openpyxl') as w:",
        "    company_contributors.to_excel(w, sheet_name='contributors', index=False)",
        "    company_contributions.to_excel(w, sheet_name='contributions', index=False)",
        "",
        "for p in sorted(TABLES_DIR.iterdir()):",
        "    print(f'  {p.relative_to(ROOT)}   {p.stat().st_size // 1024} KB')",
    ),

    md(
        "## 13. Summary",
    ),

    code(
        "total_txns    = len(saspac3)",
        "total_people  = len(stats5)",
        "total_dollars = saspac3['contribsum'].sum()",
        "n_companies   = len(ACTIVE_COMPANIES)",
        "share_D = (stats5['mParty'] == 'Democrat').mean() * 100",
        "share_R = (stats5['mParty'] == 'Republican').mean() * 100",
        "share_O = (stats5['mParty'] == 'Other').mean() * 100",
        "",
        "print('=' * 64)",
        "print(f'  Cross-company FEC analysis — {MIN_DATE} → {MAX_DATE}')",
        "print('=' * 64)",
        "print(f'  Companies analyzed   : {n_companies}')",
        "print(f'  Total transactions   : {total_txns:>10,}')",
        "print(f'  Unique contributors  : {total_people:>10,}')",
        "print(f'  Total dollars        : ${total_dollars:>12,.2f}')",
        "print(f'  Avg txns / person    : {total_txns / max(total_people, 1):>10.2f}')",
        "print()",
        "print(f'  Contributor classification (60 % rule):')",
        "print(f'    Democrat   : {share_D:>5.1f}%')",
        "print(f'    Republican : {share_R:>5.1f}%')",
        "print(f'    Other / N  : {share_O:>5.1f}%')",
        "print('=' * 64)",
    ),

]


def main() -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = CELLS
    nb.metadata.update({
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3',
        },
        'language_info': {
            'name': 'python',
            'version': '3.12',
        },
    })

    out_path = Path(__file__).resolve().parent.parent / 'notebooks' / 'cross_company.ipynb'
    nbf.write(nb, str(out_path))
    print(f'Wrote {out_path}  ({len(CELLS)} cells)')


if __name__ == '__main__':
    main()
